# Generated by Django 5.0.3 on 2024-05-26 14:14

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Is_admin')),
                ('is_medecin', models.BooleanField(default=False, verbose_name='Is medecin')),
                ('is_pharmacie', models.BooleanField(default=False, verbose_name='Is pharmacie')),
                ('is_patient', models.BooleanField(default=False, verbose_name='Is patient')),
                ('is_livreur', models.BooleanField(default=False, verbose_name='Is livreur')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id_produit', models.AutoField(primary_key=True, serialize=False)),
                ('nom_pr', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=10000, null=True)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, default=None, max_digits=10)),
                ('image', models.CharField(default=None, max_length=2000, null=True)),
                ('type', models.CharField(choices=[('Pharmaceutique', 'Produit Pharmaceutique'), ('Medicament', 'Médicament')], max_length=100)),
                ('Qte', models.CharField(blank=True, max_length=100, null=True)),
                ('dosage', models.CharField(blank=True, max_length=100, null=True)),
                ('ordonnance_requise', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacie',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nom', models.CharField(max_length=255)),
                ('heure_ouverturep', models.TimeField(blank=True, null=True)),
                ('heure_fermeturep', models.TimeField(blank=True, null=True)),
                ('nom_responsable', models.CharField(blank=True, max_length=255, null=True)),
                ('num_tel', models.CharField(blank=True, max_length=15, null=True)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('produits', models.ManyToManyField(to='app1.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Admin2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_Admin', models.CharField(default='Admin', max_length=255)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('role', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Livreur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_liv', models.CharField(max_length=100)),
                ('num_tel', models.CharField(max_length=15)),
                ('adresse_liv', models.CharField(max_length=200)),
                ('disponible', models.BooleanField(default=False)),
                ('ville', models.CharField(default='Alger', max_length=100)),
                ('user', models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_medecin', models.CharField(default='Medecin Anonyme', max_length=255)),
                ('adresse_cabinet', models.CharField(blank=True, max_length=255, null=True)),
                ('heure_ouverture', models.TimeField(blank=True, null=True)),
                ('heure_fermeture', models.TimeField(blank=True, null=True)),
                ('jours_travail', models.CharField(blank=True, max_length=255, null=True)),
                ('specialite', models.CharField(blank=True, max_length=255, null=True)),
                ('num_tel', models.CharField(blank=True, max_length=15, null=True)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_patient', models.CharField(max_length=255)),
                ('sexe', models.CharField(blank=True, max_length=1, null=True)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('num_tel', models.CharField(blank=True, max_length=15, null=True)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InfosPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('sexe', models.CharField(max_length=10, null=True)),
                ('num_tel', models.CharField(max_length=20)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app1.patient')),
            ],
        ),
        migrations.CreateModel(
            name='PharmaCommandes',
            fields=[
                ('id_commandepharm', models.AutoField(primary_key=True, serialize=False)),
                ('nom_utilisateur', models.CharField(default=None, max_length=100)),
                ('prenom_utilisateur', models.CharField(default=None, max_length=100)),
                ('total', models.CharField(default=None, max_length=200)),
                ('date_commande', models.DateTimeField(auto_now=True)),
                ('ville', models.CharField(max_length=100)),
                ('adr_mail', models.CharField(default=None, max_length=100)),
                ('adresse', models.CharField(default=None, max_length=100)),
                ('num_tel', models.CharField(max_length=15, null=True)),
                ('items', models.CharField(default=None, max_length=300)),
                ('ordonnance', models.FileField(blank=True, null=True, upload_to='ordonnances/')),
                ('etat', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ACCEPTE', 'Accepté'), ('EN_COURS_DE_LIVRAISON', 'En cours de livraison'), ('ACCEPTEE PAR LE LIVREUR ', 'Accéptée par le livreur'), ('REFUSEE PAR LE LIVREUR', 'Refusée par le livreur'), ('LIVRE', 'Livré')], default='EN_ATTENTE', max_length=200)),
                ('livreur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.livreur')),
                ('pharmacie', models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='app1.pharmacie')),
            ],
            options={
                'ordering': ['-date_commande'],
            },
        ),
        migrations.AddField(
            model_name='patient',
            name='commandes',
            field=models.ManyToManyField(to='app1.pharmacommandes'),
        ),
        migrations.CreateModel(
            name='Produit_Prescris',
            fields=[
                ('produit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='app1.produit')),
                ('id_produitprescris', models.AutoField(primary_key=True, serialize=False)),
                ('nom_prp', models.CharField(max_length=100)),
                ('Descriptionp', models.CharField(max_length=10000, null=True)),
            ],
            bases=('app1.produit',),
        ),
        migrations.CreateModel(
            name='Ordonnance',
            fields=[
                ('id_ordonnance', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('infos_patient', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app1.infospatient')),
                ('medecin', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app1.medecin')),
                ('produits', models.ManyToManyField(to='app1.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id_commande', models.AutoField(primary_key=True, serialize=False)),
                ('nom_utilisateur', models.CharField(default=None, max_length=100)),
                ('total', models.CharField(default=None, max_length=200)),
                ('date_commande', models.DateTimeField(auto_now=True)),
                ('ville', models.CharField(max_length=100)),
                ('adr_mail', models.CharField(default=None, max_length=100)),
                ('adresse', models.CharField(default=None, max_length=100)),
                ('num_tel', models.CharField(max_length=15, null=True)),
                ('items', models.CharField(default=None, max_length=300)),
                ('pharmacie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='app1.pharmacie')),
            ],
            options={
                'ordering': ['-date_commande'],
            },
        ),
    ]
