# Generated by Django 5.0.3 on 2024-05-26 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_remove_infospatient_sexe'),
    ]

    operations = [
        migrations.AddField(
            model_name='infospatient',
            name='sexe',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
