# Generated by Django 5.0.3 on 2024-05-26 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_infospatient_sexe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infospatient',
            name='num_tel',
        ),
    ]
