# Generated by Django 5.0.3 on 2024-05-28 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_messagerie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordonnance',
            name='produits',
            field=models.ManyToManyField(to='app1.produit_prescris'),
        ),
    ]
