# Generated by Django 5.0.3 on 2024-05-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_ordonnance_produits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordonnance',
            name='produits',
        ),
        migrations.AddField(
            model_name='ordonnance',
            name='produits',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
