# Generated by Django 5.0.3 on 2024-05-28 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_remove_ordonnance_produits_ordonnance_produits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordonnance',
            name='produits',
        ),
        migrations.AddField(
            model_name='ordonnance',
            name='produits',
            field=models.ManyToManyField(to='app1.produit_prescris'),
        ),
    ]
