# Generated by Django 5.0.3 on 2024-05-28 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_remove_ordonnance_produits_ordonnance_produits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True),
        ),
    ]
