# Generated by Django 5.0.3 on 2024-05-28 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_alter_produit_prix_unitaire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infospatient',
            name='id',
        ),
        migrations.AddField(
            model_name='infospatient',
            name='id_infos_patient',
            field=models.AutoField(default='1', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ordonnance',
            name='infos_patient',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='app1.infospatient'),
        ),
    ]
