# Generated by Django 5.0.3 on 2024-05-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_remove_infospatient_id_infospatient_id_infos_patient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infospatient',
            name='id_infos_patient',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
