# Generated by Django 5.0.3 on 2024-05-28 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_alter_infospatient_id_infos_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infospatient',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.patient'),
        ),
    ]
