# Generated by Django 5.0.3 on 2024-05-28 14:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_alter_infospatient_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordonnance',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
